image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      flutter channel stable
      flutter --version
      flutter config --enable-web
      flutter pub get
    command: |
      flutter run -d web-server --web-hostname 0.0.0.0 --web-port 8080

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter
